### PR TITLE
Initial github workflow

### PR DESCRIPTION
**Pull request by CherryKitten**

### CODE REVIEW

**Comment by nikzen** [comment]
I disable cla check for famedly organization members - lets see if this works

**Comment by CherryKitten** [comment]
This should be in an initial mergable state now, there's still a lot missing, but at least we're getting a fail/pass on lints and the tests run.

On PR creation and update, workflows for ansible-lint and ansible-test are imported from https://github.com/famedly/github-workflows/blob/main/.github/workflows/ansible.yml.

Still todo:
- Saving output of ansible-lint and coverage reports as artifacts
- Running tests on multiple versions
- Running playbook and role lints seperatly
- Probably something small that I might have missed?

**Review by jcgruenhage — CHANGES_REQUESTED** [review]
I've looked through the workflow added here, the workflows pulled in from  github.com/famedly/github-workflows. I've not checked the ansible-test-gh-action repo in detail.

Things I noticed so far:
 - as @lrsksr  mentioned in our internal chat: We used to branches in https://gitlab.com/famedly/infra/templates/ci-cd with version numbers in them, so that we could bump the number if we had/wanted to make breaking changes to the pipeline. I think it'd make sense to replicate this here. After we've moved the workflow to a branch (`ansible-v1` for example), we should have a main branch with only a README left, which is why I'd suggest doing that now, as it'd break the workflows wherever we import it from main.
 - The actions will need some more work/cleanup later on. The lint action still contains a "test" commit from me for example, and the reverts on the test action don't conform to the conventional commit spec. These are things we can look into later though.
 - We'll need to put in some work into dependency management, but that can probably also happen later. Right now, the linting action works because we have https://gitlab.com/famedly/infra/containers/ansible-test-suite/ as a container image, which contains a bunch of pip packages. This also needs to be migrated to github, and be reduced to a smaller set of things installed in there, and then we should add collection dependencies as a parameter to the workflow.
 
 As mentioned in the three points, only the first one is something that we'd need to do now, the rest can happen later on at some point.

**Comment by jcgruenhage** [comment]
If you squash these commits together I'll approve this, looking good now :)

**Comment by CherryKitten** [comment]
> If you squash these commits together I'll approve this, looking good now :)

Done!

**Review by jcgruenhage — APPROVED** [review]

**Pull request merged**
